server.port=8080
spring.application.name=vulnseer

# customized configuration
config.ground-truth-path=/Users/yelikai/Desktop/supply_chain/source_code/VulnSEER-validation/groundtruth
config.output-dir=output
config.max-call-chain-length=10
config.max-fuzz-chain-number=20
config.max-retry-count=2

config.enable-gpt=true
config.gpt-model-name=gpt-4o-2024-11-20
config.max-fuzz-time=120000
config.max-prompt-scope=2
config.max-gpt-request-limit=3
config.max-inter-analysis-scope=3
